### ISSUE TITLE
A question about qmix_cql

### ISSUE THREAD

**Issue by zyh1999** [instadeepai/og-marl#8]
Why   `all_mixed_ood_qs.append(chosen_action_qs) # [B, T, Ra + 1]` in og_marl/tf2/systems/qmix_cql.py line 170. 
I am a little confused about this, since "chosen_action_qs" is not a "ood_action", but an  "action" in buffer.

**Comment by jcformanek** [comment]
Hi @zyh1999, thank you for posting a question. You are certainly correct that `chosen_action_q` is not an OOD action. Its been a while since I did the implementation but I believe it was done this way because we found (empirically) that the CQL loss diverged when I omitted the chosen actions Q-value from the log_sum_exp term. And I was inspired to add it to the log_sum_exp term since in the single agent DQN-CQL implementation (see [here](https://github.com/BY571/CQL/blob/main/CQL-DQN/agent.py) ) the log_sum_exp calculation is done across all Q-values (which includes the chosen action Q-value). Having said that, I do not have a good theoretical justification for doing it this way. So if you find a better way of doing it, or that performance is better when omitting it, then please do let us know.

**Comment by zyh1999** [comment]
Well, I know the reason.  Yesterday, I conducted an experiment and found that removing the CQL loss led to divergence. Thank you very much for your prompt response!

**Comment by jcformanek** [comment]
Its my pleasure. Please let me know if you have any further questions or you have any trouble getting the code to run on some configuration.
